---
- name: Install and configure Nginx
  hosts: webservers
  become: yes

  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Change Nginx port from 80 to 8081
      ansible.builtin.replace:
        path: /etc/nginx/sites-available/default
        regexp: 'listen 80 default_server;'
        replace: 'listen 8081 default_server;'

    - name: Deploy application
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
